### ISSUE TITLE
There may be an error in line 268 in dialog_teacher.py

### ISSUE THREAD

**Issue by Chen-Wang-CUHK** [facebookresearch/ParlAI#64]
**opt**.get('no_images', False)  should be **self.opt**.get('no_images', False) ?

**Comment by jiasenlu** [comment]
Thanks, Yes, this was type fixed in #54, waiting to merge to the master.

**Comment by Chen-Wang-CUHK** [comment]
And it seems that you forgot "*import os*" because you used *os.path *in
line 299.

2017-05-12 15:27 GMT+08:00 Jiasen Lu <notifications@github.com>:

**Comment by alexholdenmiller** [comment]
Thanks Chen-Wang! Good catch

**Comment by alexholdenmiller** [comment]
both of these should be fixed now
